-- DDL generated by Postico 1.5.5
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE games (
    id uuid PRIMARY KEY,
    teacherid uuid NOT NULL REFERENCES teachers(id),
    name character varying(64) NOT NULL,
    gametype character varying(64) NOT NULL,
    options jsonb,
    code character(6) NOT NULL
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX games_pkey ON games(id uuid_ops);

-- DDL generated by Postico 1.5.5
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE games_played (
    id uuid PRIMARY KEY,
    studentid uuid NOT NULL REFERENCES students(id),
    gameid uuid NOT NULL REFERENCES games(id),
    results jsonb
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX games_played_pkey ON games_played(id uuid_ops);

-- DDL generated by Postico 1.5.5
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE students (
    id uuid PRIMARY KEY,
    firstname character varying(64),
    lastname character varying(64),
    username character varying(128),
    password character(60)
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX students_pkey ON students(id uuid_ops);

-- DDL generated by Postico 1.5.5
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE teacher_student_bridge (
    id SERIAL PRIMARY KEY,
    teacherid uuid NOT NULL REFERENCES teachers(id) ON UPDATE CASCADE,
    studentid uuid NOT NULL REFERENCES students(id) ON UPDATE CASCADE
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX teacher_student_bridge_pkey ON teacher_student_bridge(id int4_ops);


-- DDL generated by Postico 1.5.5
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE teachers (
    id uuid PRIMARY KEY,
    firstname character varying(64),
    lastname character varying(64),
    email character varying(128),
    password character(60)
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX teachers_pkey ON teachers(id uuid_ops);
